## 标量

In [3]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
print(x)

x + y, x * y, x / y, x ** y

tensor(3.)


(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

## 向量

In [4]:
#通过一维张量表示向量。一般来说，张量可以具有任意长度，取决于机器的内存限制。
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
y = torch.arange(24).reshape(2,3,4)
print(y)
y.shape

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


torch.Size([2, 3, 4])

In [9]:
y.mean(dtype=float, dim=0)

tensor([[ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.]], dtype=torch.float64)

## 矩阵

In [10]:
A = torch.arange(20).reshape(5, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [11]:
#矩阵的转置
A.T 

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [12]:
#对称矩阵
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


In [13]:
sum(B == B.T)

tensor([3, 3, 3])

## 张量

In [14]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [15]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [16]:
A*2

tensor([[ 0.,  2.,  4.,  6.],
        [ 8., 10., 12., 14.],
        [16., 18., 20., 22.],
        [24., 26., 28., 30.],
        [32., 34., 36., 38.]])

In [17]:
#两个矩阵的按元素乘法称为Hadamard积
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [18]:
#将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。
a = 2
X = torch.arange(24).reshape(2,3,4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

## 降维

In [19]:
x = torch.arange(4)
x, x.sum()

(tensor([0, 1, 2, 3]), tensor(6))

In [20]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [21]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [22]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [23]:
A.sum(dim=[0,1])

tensor(190.)

In [26]:
A.mean(), A.sum()/A.numel()

(tensor(9.5000), tensor(9.5000))

In [29]:
print(len(A))
A.numel()

5


20

In [32]:
A.mean(axis=0), A.sum(axis=0)/A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [33]:
#非降维求和
sum_A = A.sum(axis=1,keepdims=True)
print(sum_A)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])


In [34]:
#由于sum_A在对每行进行求和后仍保持两个轴，我们可以通过广播将A除以sum_A。

A/sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [39]:
#沿某个轴计算A元素的累积总和， 比如axis=0（按行计算），
#可以调用cumsum函数。 此函数不会沿任何轴降低输入张量的维度。
print(A)
A.cumsum(axis=0)


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [42]:
C = torch.arange(24).reshape(2,3,4)
print(C)
C.cumsum(dim=1)


tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


tensor([[[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21]],

        [[12, 13, 14, 15],
         [28, 30, 32, 34],
         [48, 51, 54, 57]]])

## 点积



In [58]:
x = torch.arange(4, dtype= torch.float32)
y = torch.ones(4, dtype= torch.float32)
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [60]:
torch.sum(x)

tensor(6.)

In [61]:
x.sum()

tensor(6.)

In [62]:
x*y

tensor([0., 1., 2., 3.])

In [63]:
torch.sum(x*y)

tensor(6.)

## 矩阵-向量积

In [65]:
A.shape, x.shape, torch.mv(A, x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

## 矩阵-矩阵乘法

V.S. Hadamard积：按元素乘法

In [68]:
B = torch.ones(4,3)
C = torch.mm(A,B)
print(C)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [69]:
A.shape, B.shape, C.shape

(torch.Size([5, 4]), torch.Size([4, 3]), torch.Size([5, 3]))

## 范数
（norm）

欧几里得距离：L2范数【向量元素平方和的平方根】

L1范数：向量元素绝对值之和

Lp范数

In [70]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [72]:
torch.abs(u).sum()

tensor(7.)

In [75]:
A = torch.arange(24).reshape(2,3,4)
A.sum()

tensor(276)

矩阵的范数

In [78]:
torch.norm(torch.ones((4,9)))

tensor(6.)

## 练习

In [93]:
#1
A = torch.arange(12).reshape(3,4)
torch.sum(A.T.T == A)/ torch.numel(A) == 1



tensor(True)

In [100]:
#2 
A = torch.randn(3,4)
B = torch.randn(3,4)
torch.sum(A.T + B.T == (A+B).T)/ torch.numel(A) == 1


tensor(True)

In [103]:
#3
A = torch.randn(3,3)
A + A.T ==(A + A.T).T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [104]:
import torch
import random

# 随机生成行数和列数
rows = random.randint(2, 6)
cols = random.randint(2, 6)

A = torch.randn(rows, cols)
print(f"shape: {A.shape}")
print(A)

shape: torch.Size([3, 2])
tensor([[-0.0121,  0.0342],
        [-0.5844,  0.9993],
        [ 1.5176,  2.5319]])


In [109]:
#4 5
C = torch.randn(2,3,4)
len(C) == C.shape[0]

True

In [115]:
#6
A = torch.arange(20).reshape(4,5)
print(A)
A/A.sum(axis=1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])


RuntimeError: The size of tensor a (5) must match the size of tensor b (4) at non-singleton dimension 1

In [123]:
#7
A = torch.arange(24,dtype=float).reshape(2,3,4)
A.sum(axis=0).shape, A.sum(axis=1).shape, A.sum(axis=2).shape

(torch.Size([3, 4]), torch.Size([2, 4]), torch.Size([2, 3]))

In [ ]:
#8
torch.linalg.norm(A)
#不管张量形状是什么，torch.linalg.norm 默认把所有元素展平，算一个总体的"大小"。


tensor(65.7571, dtype=torch.float64)

## 检测题

In [143]:
A = torch.randn(3,4)
print(torch.sum((A.T).T == A) / torch.numel(A) == 1)
print(((A.T).T == A).sum())
print(torch.sum((A.T).T == A))

# A + A.T ==(A +A.T).T


tensor(True)
tensor(12)
tensor(12)


In [135]:
A = torch.randn(4,4)
M = A + A.T
print((M == M.T).all())
#.all()更简洁，直接判断“是否所有元素都是true”

tensor(True)
