In [40]:
import torch

x = torch.arange(12) #生成一个从 0 到 11 的一维张量（和 Python 的 range(12) 类似，但生成的是张量）
print(x)
print(x.shape)
print(x.numel()) #张量里总共有多少个数字（number of elements），

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12


In [41]:
X = x.reshape(3,4)
print(X)
print(X.shape)
#大写 X 表示矩阵，小写 x 表示向量

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


In [42]:
Y = torch.zeros((2,3,4))
print(Y)

torch.zeros((2, 3, 4))   # 全 0，形状 2×3×4
torch.ones((2, 3, 4))    # 全 1
torch.randn(3, 4)        # 随机数（标准正态分布，后面讲）均值0，标准差1
torch.tensor([[1, 2, 3], [4, 5, 6]])   # 从 Python 列表直接造

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [43]:
Z = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(Z)

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


In [44]:
#1
x = torch.arange(20)
A = x.reshape(4, 5)
print("A =", A)
B = x.reshape(2, 10)
print("B =", B)
C = x.reshape(5, -1)
print("C =", C)

A = tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
B = tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
C = tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


In [45]:
#2
A = torch.ones((2,3,4))
print(A)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


In [46]:
#3
y = torch.arange(15)
Y = y.reshape(3, 5)

In [47]:
#4
X = torch.randn((3, 4))
print(X)

tensor([[-0.2806,  0.5620,  1.2473, -1.0097],
        [-0.1696, -0.0419, -0.3331, -1.4195],
        [ 0.7984,  0.5541, -0.8677, -1.1330]])


In [48]:
#用“随机种子”（seed）固定随机数
torch.manual_seed(42)
X1 = torch.randn(3,4)
print(X1)

torch.manual_seed(42)
X2 = torch.randn(3, 4)
print(X2)


tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])
tensor([[ 0.3367,  0.1288,  0.2345,  0.2303],
        [-1.1229, -0.1863,  2.2082, -0.6380],
        [ 0.4617,  0.2674,  0.5349,  0.8094]])


## 索引和切片

In [49]:
x = torch.arange(10)
print(x)
print()
print(x[0])
print(x[-1])
print(x[2:5])
print(x[:3])
print(x[3:])
print(x[::2])


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

tensor(0)
tensor(9)
tensor([2, 3, 4])
tensor([0, 1, 2])
tensor([3, 4, 5, 6, 7, 8, 9])
tensor([0, 2, 4, 6, 8])


In [50]:
x = torch.arange(12).reshape(3, 4)
print(x)
print(x[1, 2])
#核心语法：X[行, 列]，用逗号分隔不同维度的索引。

Y = torch.arange(24).reshape(2,3,4)
print(Y)
print(Y[:, 0, :])

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(6)
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[ 0,  1,  2,  3],
        [12, 13, 14, 15]])


In [51]:
#修改张量的值
X = torch.arange(12).reshape(3,4)
X[1, 2] = 99
print(X)
X[0, :]=0
print(X)
X[:, 0] = torch.tensor([100,200,300])
print(X)

tensor([[ 0,  1,  2,  3],
        [ 4,  5, 99,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  0,  0,  0],
        [ 4,  5, 99,  7],
        [ 8,  9, 10, 11]])
tensor([[100,   0,   0,   0],
        [200,   5,  99,   7],
        [300,   9,  10,  11]])


In [52]:
print("1.")
X = torch.arange(20).reshape(4,5)
print(X[1])
print(X[:,2])
print(X[-2:, -2:])

print("2.")
X[0] = -1
X[:, 2] = 0
print(X)

print("3.")
Y = torch.arange(24).reshape(2,3,4)
print(Y[1,2])
print(Y[:,:,-1])
print(Y[0, -2:, -2:])

print("4.")
batch = torch.randn(8, 3, 32, 32)
print(batch[5])
print(batch[:,1,:,:])
print(batch[0, :, :16, :16])




1.
tensor([5, 6, 7, 8, 9])
tensor([ 2,  7, 12, 17])
tensor([[13, 14],
        [18, 19]])
2.
tensor([[-1, -1,  0, -1, -1],
        [ 5,  6,  0,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16,  0, 18, 19]])
3.
tensor([20, 21, 22, 23])
tensor([[ 3,  7, 11],
        [15, 19, 23]])
tensor([[ 6,  7],
        [10, 11]])
4.
tensor([[[ 1.2984, -0.2309, -1.7903,  ..., -0.9776,  1.2013, -2.0408],
         [-0.4775, -0.3340, -0.7425,  ...,  0.7126, -0.2536,  3.2119],
         [ 0.6260, -1.3800,  1.0138,  ...,  0.8188,  0.6263, -0.5643],
         ...,
         [-0.7888,  1.2763, -1.1211,  ..., -0.5381,  0.3236, -0.7699],
         [-1.0488, -0.4038,  1.0136,  ...,  0.4645, -1.8276, -0.5610],
         [ 0.0454,  0.2732,  0.9194,  ...,  0.3542, -0.9313, -0.0058]],

        [[ 0.0303,  0.9827, -0.5459,  ...,  0.1658, -1.5030, -0.6064],
         [-0.2777,  1.9225,  0.5505,  ...,  0.5437,  1.4505, -1.6918],
         [ 0.7203,  1.6914, -1.8721,  ..., -1.0671,  0.0121,  0.8624],
         ...,
     

In [53]:
X = torch.arange(20).reshape(4,5)
print(X[:,2].shape)
print(X[:,2:3].shape) #保留维度

torch.Size([4])
torch.Size([4, 1])


## 张量运算
形状相同的张量

In [54]:

x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])

print(x + y)
print(x - y)
print(x / y)
print(x * y)
print(x ** y)
torch.exp(x)


tensor([ 3.,  4.,  6., 10.])
tensor([-1.,  0.,  2.,  6.])
tensor([0.5000, 1.0000, 2.0000, 4.0000])
tensor([ 2.,  4.,  8., 16.])
tensor([ 1.,  4., 16., 64.])


tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [55]:
#张量拼接
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(torch.cat((X, Y),dim=0))
torch.cat((X, Y), dim=1)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])


tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])

In [56]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [57]:
M = torch.arange(24).reshape((2,3,4))
N = torch.randn(2,3,4) 
print(M <= N)
print(M + N)

tensor([[[ True, False, False, False],
         [False, False, False, False],
         [False, False, False, False]],

        [[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]])
tensor([[[ 1.4660,  1.2230,  3.3928,  1.2502],
         [ 3.7597,  7.7975,  5.4550,  6.9279],
         [ 5.9946,  9.0326, 10.4357, 11.1141]],

        [[12.4115, 13.3144, 13.6813, 15.3934],
         [16.9189, 18.0818, 18.8255, 18.8774],
         [20.4169, 21.7319, 22.5414, 22.5296]]])


In [58]:
print(M)
print(N)
torch.cat((M, N), dim=2)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 1.4660,  0.2230,  1.3928, -1.7498],
         [-0.2403,  2.7975, -0.5450, -0.0721],
         [-2.0054,  0.0326,  0.4357,  0.1141]],

        [[ 0.4115,  0.3144, -0.3187,  0.3934],
         [ 0.9189,  1.0818,  0.8255, -0.1226],
         [ 0.4169,  0.7319,  0.5414, -0.4704]]])


tensor([[[ 0.0000,  1.0000,  2.0000,  3.0000,  1.4660,  0.2230,  1.3928,
          -1.7498],
         [ 4.0000,  5.0000,  6.0000,  7.0000, -0.2403,  2.7975, -0.5450,
          -0.0721],
         [ 8.0000,  9.0000, 10.0000, 11.0000, -2.0054,  0.0326,  0.4357,
           0.1141]],

        [[12.0000, 13.0000, 14.0000, 15.0000,  0.4115,  0.3144, -0.3187,
           0.3934],
         [16.0000, 17.0000, 18.0000, 19.0000,  0.9189,  1.0818,  0.8255,
          -0.1226],
         [20.0000, 21.0000, 22.0000, 23.0000,  0.4169,  0.7319,  0.5414,
          -0.4704]]])

In [59]:
X.sum()

tensor(66.)

## 广播机制

In [60]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [61]:
#沿数组中长度为1的轴进行广播
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 节省内存

In [62]:
before = id(Y)
print(before)
Y = Y + X
print(id(Y))

2396226750000
2396226748640


In [63]:
#用切片表示法将操作的结果分配给原先分配的数组：执行原地操作
Z = torch.zeros_like(Y)
print("id(Z):", id(Z))
Z[:] = X+Y
print("id(Z):", id(Z))

id(Z): 2396226749760
id(Z): 2396226749760


In [64]:
before = id(X)
X += Y
id(X) == before

True

In [65]:
#这三种等价：
X[:] = X + Y
X += Y
X.add_(Y)

tensor([[ 8.,  9., 26., 27.],
        [24., 33., 42., 51.],
        [56., 57., 58., 59.]])

## 转换为其他Python对象

In [66]:
A = X.numpy()
B = torch.tensor(A)
C = B.numpy()
print(X)
print(A)
type(A), type(B), type(C)


tensor([[ 8.,  9., 26., 27.],
        [24., 33., 42., 51.],
        [56., 57., 58., 59.]])
[[ 8.  9. 26. 27.]
 [24. 33. 42. 51.]
 [56. 57. 58. 59.]]


(numpy.ndarray, torch.Tensor, numpy.ndarray)

In [67]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 练习


In [68]:
#2
imgs = torch.randn(100, 3, 64, 64)
imgs[50]
imgs[:,2,:,:]
imgs[:50], imgs[50:]

(tensor([[[[-1.1442e+00, -8.6287e-01, -3.2543e-02,  ..., -6.7062e-01,
            -5.4980e-01, -1.0136e+00],
           [-8.4757e-01, -7.4559e-02,  1.6060e+00,  ...,  6.5495e-02,
             1.2327e+00,  1.5566e+00],
           [-1.2382e+00, -1.3372e+00,  1.5225e-01,  ..., -1.5389e+00,
            -5.5428e-01,  4.7813e-01],
           ...,
           [ 2.2873e+00,  2.8704e-01,  5.7375e-01,  ...,  3.6994e-01,
             5.2067e-01,  1.7841e+00],
           [-9.5069e-01, -6.4121e-01,  6.7615e-01,  ...,  1.6346e+00,
             1.7163e+00,  5.2874e-01],
           [ 3.6174e-01,  2.8426e-02,  7.8624e-01,  ..., -4.6257e-01,
             9.0704e-02,  4.1435e-01]],
 
          [[-3.1268e-01,  1.0867e+00,  1.2147e+00,  ...,  4.4297e-01,
             1.6820e+00,  1.9812e+00],
           [-1.5535e+00,  1.2849e+00, -2.3826e-01,  ..., -6.3258e-01,
            -7.7525e-01, -2.5654e-02],
           [ 3.5578e-01,  5.2087e-01,  7.9629e-01,  ...,  2.3214e+00,
             5.1889e-01,  2.6082e+00],


dim=K，就是把 shape 里第 K 个数字"消掉"

In [69]:
A = torch.arange(12).reshape(3,4)
print(A)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [70]:
A.sum()
#单个数字，shape是（）--0维张量

tensor(66)

In [71]:
print(A.sum(dim=0))
print(A.sum(dim=0).shape)

tensor([12, 15, 18, 21])
torch.Size([4])


In [72]:
A.sum(dim=1)

tensor([ 6, 22, 38])

## 又一个练习

In [78]:
#1
A = torch.arange(12).reshape(3,4)
print(A[1])
print(A[:,1])
A[0] = 99
print(A)
print(A.reshape(2,6))
print(A.reshape(2,2,3))


tensor([4, 5, 6, 7])
tensor([1, 5, 9])
tensor([[99, 99, 99, 99],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[99, 99, 99, 99,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
tensor([[[99, 99, 99],
         [99,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])


In [74]:
#2
A = torch.arange(6).reshape(3,2)
B = torch.arange(2).reshape(1,2)
A+B


tensor([[0, 2],
        [2, 4],
        [4, 6]])

In [76]:
# 代码 A
X = torch.arange(6)
before = id(X)
X = X + 1
print(id(X) == before)

# 代码 B
X = torch.arange(6)
before = id(X)
X += 1
print(id(X) == before)

False
True
