In [1]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

## 读取数据集

In [2]:
# 如果没有安装pandas，只需取消对以下行的注释来安装pandas
!pip install pandas
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


## 处理缺失值

In [3]:
#插值法
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2] #iloc=按位置取
inputs = inputs.fillna(inputs.mean(numeric_only=True)) #默认算列
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [4]:
#处理字符串（独热编码）
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0        True      False
1       2.0       False       True
2       4.0       False       True
3       3.0       False       True


In [5]:
#转成张量
import torch
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

In [6]:
N_na = data.isna().sum()
print(N_na)
print(N_na.idxmax())
#Series = 带标签的一维数据。
#可以理解成"一列数据 + 每个数据有个名字"。Pandas DataFrame多个Series拼起来。

NumRooms    2
Alley       3
Price       0
dtype: int64
Alley


In [7]:
data.drop(columns="Alley") #不改变原data，而是返回一个新的DataFrame

,NumRooms,Price
0,NaN,127500
1,2.0,106000
2,4.0,178100
3,NaN,140000


In [8]:
data_new = data.drop(columns=data.isna().sum().idxmax())
print(data_new)

   NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000


In [9]:
data['NumRooms']

0    NaN
1    2.0
2    4.0
3    NaN
Name: NumRooms, dtype: float64

## 练习


In [10]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'dirty.csv')
with open(data_file, 'w') as f:
    f.write('Age,City,Salary\n')  # 列名
    f.write('25,Beijing,8000\n')  # 每行表示一个数据样本
    f.write('NA,Shanghai,12000\n')
    f.write('30,NA,NA\n')
    f.write('NA,Beijing,10000\n')
    

In [11]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

    Age      City   Salary
0  25.0   Beijing   8000.0
1   NaN  Shanghai  12000.0
2  30.0       NaN      NaN
3   NaN   Beijing  10000.0


In [12]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
print(inputs)

    Age      City
0  25.0   Beijing
1   NaN  Shanghai
2  30.0       NaN
3   NaN   Beijing


In [13]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

    Age      City
0  25.0   Beijing
1  27.5  Shanghai
2  30.0       NaN
3  27.5   Beijing


In [14]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

    Age  City_Beijing  City_Shanghai  City_nan
0  25.0          True          False     False
1  27.5         False           True     False
2  30.0         False          False      True
3  27.5          True          False     False


In [15]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(outputs.to_numpy(dtype=float))
X, y

(tensor([[25.0000,  1.0000,  0.0000,  0.0000],
         [27.5000,  0.0000,  1.0000,  0.0000],
         [30.0000,  0.0000,  0.0000,  1.0000],
         [27.5000,  1.0000,  0.0000,  0.0000]], dtype=torch.float64),
 tensor([ 8000., 12000.,    nan, 10000.], dtype=torch.float64))

In [25]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'Scores.csv')
with open(data_file, 'w') as f:
    f.write('age,Subject,Name,Score\n')  # 列名
    f.write('12,Maths,Mary,80\n')  # 每行表示一个数据样本
    f.write('23,NA,James,NA\n')
    f.write('NA,English,Cindy,90\n')
    f.write('18,NA,Marc,NA\n')
    f.write('16,Physics,Laura,100\n')
    

In [26]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

    age  Subject   Name  Score
0  12.0    Maths   Mary   80.0
1  23.0      NaN  James    NaN
2   NaN  English  Cindy   90.0
3  18.0      NaN   Marc    NaN
4  16.0  Physics  Laura  100.0


In [28]:
inputs,outputs = data.iloc[:,0:3], data.iloc[:,3]

In [30]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))
print(inputs)

     age  Subject   Name
0  12.00    Maths   Mary
1  23.00      NaN  James
2  17.25  English  Cindy
3  18.00      NaN   Marc
4  16.00  Physics  Laura


In [36]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

     age  Subject_English  Subject_Maths  Subject_Physics  Subject_nan  \
0  12.00            False           True            False        False   
1  23.00            False          False            False         True   
2  17.25             True          False            False        False   
3  18.00            False          False            False         True   
4  16.00            False          False             True        False   

   Name_Cindy  Name_James  Name_Laura  Name_Marc  Name_Mary  Name_nan  
0       False       False       False      False       True     False  
1       False        True       False      False      False     False  
2        True       False       False      False      False     False  
3       False       False       False       True      False     False  
4       False       False        True      False      False     False  


In [40]:
X = torch.tensor(inputs.to_numpy(dtype=float))
print(X)
y = torch.tensor(outputs.to_numpy(dtype=float))
print(y)

tensor([[12.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
          0.0000,  1.0000,  0.0000],
        [23.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  1.0000,  0.0000,
          0.0000,  0.0000,  0.0000],
        [17.2500,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,
          0.0000,  0.0000,  0.0000],
        [18.0000,  0.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,
          1.0000,  0.0000,  0.0000],
        [16.0000,  0.0000,  0.0000,  1.0000,  0.0000,  0.0000,  0.0000,  1.0000,
          0.0000,  0.0000,  0.0000]], dtype=torch.float64)
tensor([ 80.,  90.,  90.,  90., 100.], dtype=torch.float64)
